accounts/urls.py
from django.urls import path

from . import views

# app_name = 'main'  # -> 'main:app_name'

urlpatterns = [
    path("register/", views.RegisterUserView.as_view(), name="register"),
    path("verify-code/", views.VerifyCodeView.as_view(), name="verify_code"),
    path("login/", views.LoginUserView.as_view(), name="login"),
    path("logout/", views.LogoutUserView.as_view(next_page="index"), name="logout"),
    path("myaccount/", views.MyAccountRedirectView.as_view(), name="myaccount"),
    path("profile/<int:pk>", views.ProfileView.as_view(), name="profile"),
    path(
        "update-profile/", views.UserProfileUpdateView.as_view(), name="update_profile"
    ),
    path(
        "add-company/", views.CreateBusinessAccountView.as_view(), name="create-company"
    ),
    path(
        "product-edit/<int:pk>", views.EditProductsView.as_view(), name="product-edit"
    ),
    path(
        "rate/<int:evaluator_id>/<int:user_id>/<int:grade>/",
        views.add_rating,
        name="add_rating",
    ),
    path("notification/", views.notification_list, name="notification"),
    path("send-message/", views.SendNotificationView.as_view(), name="send_message"),
    path(
        "product_phone_view_count/",
        views.product_phone_view_count,
        name="product_phone_view_count",
    ),
    path("forgot-password/", views.SendUserDataView.as_view(), name="forgot-password"),
    path("update-password/", views.update_password, name="update-password"),
    path("subscribe/<int:user_id>/", views.subscribe, name="subscribe"),
    path("complaint_view", views.complaint_view, name="complaint_view"),
    path("admin/dashboard/", views.admin_dashboard_view, name="admin_dashboard"),
    path(
        "admin/dashboard/user-list/",
        views.AdminUserListView.as_view(),
        name="admin_user_list",
    ),
    path(
        "admin/dashboard/user-verify/",
        views.AdminUserVerify.as_view(),
        name="admin_user_verify",
    ),
    path(
        "admin/dashboard/user-deleted/",
        views.AdminUserDeleted.as_view(),
        name="admin_user_deleted",
    ),
    path(
        "admin/dashboard/products-active/",
        views.AdminProductsActive.as_view(),
        name="admin_user_products_active",
    ),
    path(
        "admin/dashboard/products-moderation/",
        views.AdminProductsModeration.as_view(),
        name="admin_user_products_moderation",
    ),
    path(
        "admin/dashboard/support/",
        views.SupportView.as_view(),
        name="admin_support",
    ),
    path(
        "admin/dashboard/statistics/",
        views.AdminStatistics.as_view(),
        name="admin_statistics",
    ),
    path(
        "add-ball/<int:user_id>/",
        views.add_ball,
        name="add_ball",
    ),
    path(
        "top-up-your-account",
        views.TopUpYourAccount.as_view(),
        name="top-up-your-account",
    ),
]

root/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.utils.translation import gettext_lazy as _

urlpatterns = [
    path(_("admin/"), admin.site.urls),
    path("users/", include("accounts.urls")),
    path("support/", include("support.urls")),
    path("", include("films.urls")),
    path("accounts/", include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path("", include("films.urls")),
    path("users/", include("accounts.urls")),
)

support/urls.py
# support/urls.py
from django.urls import path
from .views import SupportView, SupportSuccessView

urlpatterns = [
    path("", SupportView.as_view(), name="support"),
    path("success/", SupportSuccessView.as_view(), name="support_success"),
]

support/models.py
from django.db import models
from django.contrib.auth import get_user_model


class SupportTicket(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    resolved = models.BooleanField(default=False)
    checked = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.username} - {self.subject}"

accounts/forms.py
import phonenumbers
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm

# from django.core.exceptions import ValidationError
from django.contrib.auth.forms import (
    UserCreationForm,
    UsernameField,
)
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from django.forms.widgets import CheckboxSelectMultiple

# from django.utils.translation import gettext as _
from django.utils.translation import gettext_lazy as _
from phonenumbers import is_valid_number
from phonenumbers.phonenumberutil import NumberParseException

from films.models import Categories, Tag, SubCategories, Country
from .models import Complaint

User = get_user_model()


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "telephone")
        widgets = {
            "username": forms.TextInput(attrs={"class": "input"}),
            "email": forms.EmailInput(attrs={"class": "input"}),
            "telephone": forms.TextInput(attrs={"class": "form-control"}),
        }

    username = UsernameField(
        widget=forms.TextInput(
            attrs={
                "class": "input",
                "placeholder": "ism_familiya",
                "type": "text",
                "autocomplete": "off",
                "name": "custom-username-field",  # Уникальное значение для имени поля
                "id": "custom-username-field",  # Уникальное значение для идентификатора поля
            }
        )
    )

    def clean_username(self):
        username = self.cleaned_data.get("username")

        # Проверяем, что имя пользователя не содержит пробелов
        if " " in username:
            raise forms.ValidationError("Имя пользователя не может содержать пробелы.")

        # Проверяем уникальность имени пользователя
        user = User
        # if User.objects.filter(username=username).exists():
        if user.objects.filter(username=username).exists():
            raise forms.ValidationError("Это имя пользователя уже занято.")

        return username

    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                "class": "input",
                "type": "email",
                "placeholder": "user@gmail.com",
                "autocomplete": "email",
            }
        )
    )

    telephone = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "input",
                "placeholder": "телефон номер или @имя пользователя",
            }
        )
    )

    password1 = forms.CharField(
        label=_("Password"),
        strip=True,
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "new-password",
                "class": "input",
                "placeholder": "Пароль",
            }
        ),
        validators=[
            MinLengthValidator(
                limit_value=8, message="Пароль должен содержать минимум 8 символов."
            )
        ],
    )

    password2 = None

    # password2 = forms.CharField(
    #     label=_("Password confirmation"),
    #     widget=forms.PasswordInput(attrs={
    #         "autocomplete": "new-password",
    #         "class": "input",
    #         "placeholder": "Подтвердите пароль",
    #     }),
    # )

    def clean_telephone(self):
        telephone = self.cleaned_data.get("telephone")

        try:
            parsed_telephone = phonenumbers.parse(telephone, None)
            if phonenumbers.is_valid_number(parsed_telephone):
                formatted_telephone = phonenumbers.format_number(
                    parsed_telephone, phonenumbers.PhoneNumberFormat.E164
                )
                return formatted_telephone
        except NumberParseException:
            pass

        raise ValidationError(_("Пожалуйста, введите правильный номер телефона."))

    def clean_email(self):
        email = self.cleaned_data.get("email")

        user = User
        # if User.objects.filter(email=email).exists():
        if user.objects.filter(email=email).exists():
            raise ValidationError(_("Этот email уже используется."))

        return email


class UserLoginForm(AuthenticationForm):
    username = UsernameField(
        widget=forms.TextInput(
            attrs={
                "autofocus": True,
                "class": "input",
                "placeholder": "Имя пользователя",
            }
        )
    )

    password = forms.CharField(
        label=_("Password"),
        strip=True,
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "current-password",
                "class": "password",
                "placeholder": "Пароль",
                "type": "password",
            }
        ),
        error_messages={
            "required": _('Поле "Пароль" обязательно для заполнения.'),
            "invalid": _("Неверный формат пароля."),
        },
    )


class CompanyInfoForm(forms.ModelForm):
    class Meta:
        # model = User()
        model = User
        fields = ["company_name", "category", "sub_category", "tags"]

    company_name = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "company-input", "id": "id_company_name"}
        ),
        required=False,
    )

    category = forms.ModelChoiceField(
        queryset=Categories.objects.filter(is_linked=True),
        empty_label="Выберите категорию",
        widget=forms.Select(attrs={"class": "company-select", "id": "id_category"}),
        required=False,
    )

    subcategories = forms.ModelChoiceField(
        queryset=SubCategories.objects.all(),  # Replace with your actual queryset
        widget=forms.Select(attrs={"class": "company-select", "id": "id_sub_category"}),
        required=False,
    )

    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=CheckboxSelectMultiple(
            attrs={"class": "company-input", "id": "id_tags"}
        ),
        error_messages={
            "required": "Выберите хотя бы один тег.",
        },
        required=False,
    )


def validate_phone_number(value):
    try:
        # Попробуйте разобрать введенный номер телефона
        parsed_number = phonenumbers.parse(value, None)

        # Проверьте, является ли разобранный номер действительным
        if not is_valid_number(parsed_number):
            raise ValidationError("Введите корректный номер телефона")
    except phonenumbers.phonenumberutil.NumberParseException:
        raise ValidationError("Введите корректный номер телефона")


class ContactInfoForm(forms.ModelForm):
    class Meta:
        # model = User()
        model = User
        fields = ["telegram", "whatsapp", "website", "url_maps"]

    telegram = forms.CharField(
        widget=forms.TextInput(attrs={"class": "company-input", "id": "id_telegram"}),
        # validators=[validate_phone_number],  # Валидатор для проверки, что это номер телефона
        error_messages={"invalid": "Введите корректный номер телефона"},
        required=False,
    )
    whatsapp = forms.CharField(
        widget=forms.TextInput(attrs={"class": "company-input", "id": "id_whatsapp"}),
        # validators=[validate_phone_number],
        error_messages={"invalid": "Введите корректный номер телефона"},
        required=False,
    )
    website = forms.CharField(
        widget=forms.TextInput(attrs={"class": "company-input", "id": "id_website"}),
        # validators=[URLValidator()],  # Валидатор для проверки, что это ссылка
        error_messages={"invalid": "Введите корректную ссылку"},
        required=False,
    )
    url_maps = forms.CharField(
        widget=forms.TextInput(attrs={"class": "company-input", "id": "id_url_maps"}),
        # validators=[URLValidator()],  # Валидатор для проверки, что это ссылка
        error_messages={"invalid": "Введите корректную ссылку"},
        required=False,
    )


def validate_logo_size(value):
    max_size = 2 * 1024 * 1024  # 2 MB
    if value.size > max_size:
        raise forms.ValidationError("Файл слишком большой. Максимальный размер: 2 МБ.")


def validate_banner_size(value):
    max_size = 4 * 1024 * 1024  # 4 MB
    if value.size > max_size:
        raise forms.ValidationError("Файл слишком большой. Максимальный размер: 4 МБ.")


class LogoForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["logo"]

    logo = forms.ImageField(
        widget=forms.ClearableFileInput(
            attrs={"id": "input-file", "hidden": "true", "accept": "image/*"}
        ),
        error_messages={
            "invalid_image": "Формат файла не поддерживается. Разрешенные форматы: jpg, png, gif и другие изображения.",
        },
        validators=[validate_logo_size],
        required=False,
    )


class BannerForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["banner"]

    # Установка атрибутов виджета и текста ошибки на уровне класса
    banner = forms.ImageField(
        widget=forms.ClearableFileInput(
            attrs={"id": "input-file", "hidden": "true", "accept": "image/*"}
        ),
        error_messages={
            "invalid_image": "Формат файла не поддерживается. Разрешенные форматы: jpg, png, gif и другие изображения."
        },
        validators=[validate_banner_size],
        # required=False,
    )


class DescriptionCountryForm(forms.ModelForm):
    class Meta:
        # model = User()
        model = User
        fields = ["description", "country"]

    description = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "class": "form-textarea",
                "placeholder": _("Введите описание"),
                "rows": "4",
            }
        ),
        max_length=800,
        required=False,
    )

    country = forms.ModelChoiceField(
        queryset=Country.objects.all(),

support/forms.py
from django import forms
from .models import SupportTicket


class SupportTicketForm(forms.ModelForm):
    class Meta:
        model = SupportTicket
        fields = ["subject", "message"]

support/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import SupportTicket
from .forms import SupportTicketForm


class SupportView(View):
    template_name = "support/support_form.html"

    def get(self, request, *args, **kwargs):
        form = SupportTicketForm()
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = SupportTicketForm(request.POST)
        if form.is_valid():
            support_ticket = form.save(commit=False)
            support_ticket.user = request.user
            support_ticket.save()
            return redirect("support_success")
        return render(request, self.template_name, {"form": form})


class SupportSuccessView(View):
    template_name = "support/support_success.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

accounts/templates/user/add-ball.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
          integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <title>Add ball</title>
    <link rel="stylesheet" href="{% static "css/product/style.css" %}">
    <link rel="stylesheet" href="{% static "css/product/main.css" %}">

</head>
<style>
    #paymentSection {
        padding: 150px 0;
        display: flex;
        justify-content: center;
    }

    #paymentContainer {
        display: flex;
        gap: 25px;
        background-color: #e8efff;
        border-radius: 22px;
        padding: 0 20px 20px 20px;
        width: max-content;
    }

    #instructionDiv {
        min-width: 300px
    }

    ol li {
        padding: 5px 0;
    }

    .pay {
        font-size: 18px;
        font-weight: 400;
        text-align: center;
    }

    #id_photo {
        border: 1px #CCC solid;
        border-radius: 22px;
    }

    #id_photo::file-selector-button {
        padding: 5px;
        border: 1px #CCC solid;
        border-radius: 22px;
    }

    /* Стилизация для контейнера */
    .file-input-container {
        position: relative;
        overflow: hidden;
        display: inline-block;
    }

    /* Стилизация для input[type="file"] */
    .file-input-container input[type="file"] {
        font-size: 100px;
        position: absolute;
        left: 0;
        top: 0;
        opacity: 0;
    }

    /* Стилизация для фейковой кнопки */
    .file-input-container .file-input-text {
        display: inline-block;
        padding: 10px;
        background-color: #0a24b9;
        color: white;
        border: none;
        border-radius: 22px;
        cursor: pointer;
    }

    {#------------------------------------------------#}
    #preview {
        transition: opacity 0.5s ease-in-out;
        cursor: pointer;
    }

    .modal {
        display: none;
        position: fixed;
        z-index: 1;
        padding: 20px;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgb(0, 0, 0);
        background-color: rgba(0, 0, 0, 0.9);
    }

    .modal-content {
        max-width: 100%;
        max-height: 100%;
        margin: auto;
        display: block;
    }

    .close {
        position: absolute;
        top: 100px;
        right: 50px;
        color: #f1f1f1;
        font-size: 40px;
        font-weight: bold;
        cursor: pointer;
    }


    {#------------------------------------------------#}
    /* Общие стили для радиокнопок */
    .radio-container {
        display: flex;
        justify-content: space-between;
        flex-direction: column;
        gap: 20px;
        margin: 5px;
    }

    .radio-item {
        width: 100%;
    }

    .radio-label {
        cursor: pointer;
        padding: 10px;
        border: 2px solid #3498db;
        border-radius: 22px;
        transition: background-color 0.3s, color 0.3s;
        display: flex;
        align-items: center;
    }

    .radio-input {
        display: none;
    }

    /* Стили для выбранных радиокнопок */
    .radio-input:checked + .radio-label {
        background-color: #3498db;
        color: #fff;
    }

    /* Анимация для эффекта hover */
    .radio-label:hover {
        background-color: #3498db;
        color: #fff;
    }

    /* Анимация для перехода при смене состояния */
    .radio-label {
        transition: background-color 0.3s, color 0.3s;
    }

    @media only screen and (max-width: 600px) {
        #paymentContainer {
            flex-direction: column;
        }
    }
</style>

<body>
{% include "nav_bar.html" %}

<section id="paymentSection">
    <div id="paymentContainer">
        <div id="instructionDiv" class="instruction">
            <h2>Инструкция:</h2>
            <div id="userAccountInfo">
                sizning hisobingiz: {{ request.user.currency }}
            </div>
            <br>
            <br>
            <div id="paymentAmount" class="pay">
                30.000 so'm
            </div>
            <ol>
                <li>Скопируйте номер карты.</li>
                <li>
                    <span id="codeSpan1">XXXX XXXX XXXX XXX1</span>
                    <button style="border: none; background: none;" onclick="copyCode(1)"><i
                            class="fa-solid fa-copy" style="font-size: 16px"></i>
                    </button>
                    <br>
                    <br>
                    <span id="codeSpan2">XXXX XXXX XXXX XXX2</span>
                    <button style="border: none; background: none;" onclick="copyCode(2)"><i
                            class="fa-solid fa-copy" style="font-size: 16px"></i>
                    </button>
                    <br>
                    <br>

                    <span id="alternativePayment">или</span>
                    <br>
                    <img src="{% static "user/image/click.JPG" %}" alt="clickqr"
                         style="max-width: 100px; padding: 5px;">
                    <img src="{% static "user/image/payme.png" %}" alt="clickqr"
                         style="max-width: 100px; padding: 5px;">
                </li>
                <li>Скиньте скриншот чека.</li>
            </ol>
        </div>

        <div id="formContainer" class="form-container" style="min-width: 300px">
            <h2>Отправка чека</h2>
            <form action="{% url "top-up-your-account" %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <p class="file-input-container">
                    <label for="id_photo" class="file-input-text">Выбрать файл</label>
                    <input type="file" name="photo" accept="image/*" id="id_photo" onchange="previewImage()">
                </p>
                <br>
                <div id="imageModal" class="modal">
                    <span class="close" onclick="closeModal()">&times;</span>
                    <img class="modal-content" id="modalImage" style="padding-top: 100px; max-width: 470px">
                </div>
                <img id="preview" style="opacity: 0; max-width: 100px;" onclick="openModal()"/>

                <p>
                    <label>Выберите сумму:</label>
                </p>
                <div class="radio-container">
                    <div class="radio-item">
                        <label id="30.000" for="id_amount_0" class="radio-label">
                            <input type="radio" name="amount" value="30" required="" id="id_amount_0"
                                   class="radio-input" checked="">
                            30.000 so'm
                        </label>
                    </div>
                    <div class="radio-item">
                        <label id="50.000" for="id_amount_1" class="radio-label">
                            <input type="radio" name="amount" value="50" required="" id="id_amount_1"
                                   class="radio-input">
                            50.000 so'm
                        </label>
                    </div>
                    <div class="radio-item">
                        <label id="100.000" for="id_amount_2" class="radio-label">
                            <input type="radio" name="amount" value="100" required="" id="id_amount_2"
                                   class="radio-input">
                            100.000 so'm
                        </label>
                    </div>
                </div>

                <div id="submitButtonContainer">
                    <button class="form-button" type="submit" style="width: 300px;">submit</button>
                </div>
            </form>
        </div>
    </div>
</section>


{% include "footer.html" %}

<script>
    function copyCode(index) {
        var codeSpan = document.getElementById('codeSpan' + index);
        var tempInput = document.createElement('input');
        tempInput.value = codeSpan.textContent;
        document.body.appendChild(tempInput);
        tempInput.select();
        document.execCommand('copy');
        document.body.removeChild(tempInput);
        alert('Код скопирован: ' + codeSpan.textContent);
    }

    document.addEventListener("DOMContentLoaded", function () {
        var amountLabels = document.querySelectorAll('label[for^="id_amount_"]');
        var payElement = document.querySelector(".pay");


        amountLabels.forEach(function (label) {
            label.addEventListener("click", function () {
                var selectedAmount = label.textContent.trim();
                var id = label.getAttribute('id');
                {#payElement.textContent = selectedAmount + " ball --> " + id + 'sum';#}
                payElement.textContent = id + " so'm";
            });
        });
    });


    function previewImage() {
        var input = document.getElementById('id_photo');
        var preview = document.getElementById('preview');

        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                preview.src = e.target.result;
                preview.style.opacity = 1;
            };

            reader.readAsDataURL(input.files[0]);
        }
    }

    function openModal() {
        var modal = document.getElementById('imageModal');
        var modalImage = document.getElementById('modalImage');
        var preview = document.getElementById('preview');

        modal.style.display = 'block';
        modalImage.src = preview.src;
    }

    function closeModal() {
        var modal = document.getElementById('imageModal');
        modal.style.display = 'none';
    }

</script>

</body>
</html>

accounts/templates/user/login.html
{% load i18n %}
{% load static %}
{% load socialaccount %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="google-singin-client_id"
          content="1064949093248-47olpbv7o9ruglkk9g46ojcqhp1b12ev.apps.googleusercontent.com">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
          integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="stylesheet" href="{% static 'css/product/style.css' %}">
    <link rel="stylesheet" href="{% static 'user/css/authentication.css' %}">
</head>
<body>

{% include 'messages.html' %}

<section class="authentication login">
    <div class="main-header__logo">
        <a href="../..">
            <img src="{% static 'images/TECNOPROM-LOGO.png' %}" alt="logo">
        </a>
    </div>
    <div class="form login">
        <div class="form-content">
            <div class="form-text">
                <header>
                    {% translate 'Войти' %}
                </header>
            </div>
            <form action="{% url 'login' %}" method="post">
                {% csrf_token %}
                <div class="field input-field">
                    {{ login_form.username }}
                </div>

                <div class="field input-field">
                    {{ login_form.password }}
                    <div class="eye-icon">
                        <i class="fa-regular fa-eye-slash" id="togglePassword"></i>
                    </div>
                </div>

                <div class="form-link">
                    <a href="{% url 'forgot-password' %}" class="forgot-password">{% translate "Забыли пароль?" %}</a>
                </div>


                <div class="field button-field">
                    <button>{% translate "Войти" %}</button>
                </div>
            </form>

        </div>

        <div class="social-media">
            <a href="{% provider_login_url 'google' %}">
                <img src="{% static 'user/image/icons-google.svg' %}" alt="google icon">
            </a>
        </div>
    </div>

    <div class="signup-banner">
        <div class="signup" id="for-singup-page">
            <div class="signup-content">
                <img src="{% static 'images/banners/banner-ishlatilgan-uskuna.svg' %}" alt="logo" class="signup-logo">
                <div class="signup-text">
                    <p>{% translate "Don't have an account" %}?
                        <a href="{% url 'register' %}" id="toggleRegisterLink">{% translate "Signup" %}</a></p>

                </div>
            </div>

        </div>

    </div>

</section>

<script>
    document.getElementById('togglePassword').addEventListener('click', function () {
        var passwordInput = document.getElementById('id_password');

        // Изменяем атрибут type у элемента input
        if (passwordInput.type === 'password') {
            passwordInput.type = 'text';
            document.getElementById('togglePassword').classList.replace('fa-eye-slash', 'fa-eye'); // Изменяем класс на fa-eye
        } else {
            passwordInput.type = 'password';
            document.getElementById('togglePassword').classList.replace('fa-eye', 'fa-eye-slash'); // Изменяем класс на fa-eye-slash
        }
    });
</script>

<!-- Display error messages here -->
{% include 'messages.html' %}

</body>
</html>

accounts/templates/user/send-message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{#{% extends "base.html" %}#}

{#{% block content %}#}
<h2>Отправить уведомление</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Отправить</button>
</form>
{#{% endblock %}#}

</body>
</html>

accounts/templates/user/update.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
          integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>

    <link rel="stylesheet" href="{% static 'css/product/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/product/update.css' %}">
</head>
<body>

{% include 'nav_bar.html' %}

<section>
    <div class="container">
        <form action="{% url 'update_profile' %}" method="post" class="custom-form">
            {% csrf_token %}
            <div class="form-group"><label for="id_username">Username:</label>
                {{ form.username }}
                <br></div>
            <div class="form-group"><label for="id_company_name">Company name:</label>
                {{ form.company_name }}</div>
            <div class="form-group"><label for="id_description">Description:</label>
                {{ form.description }}</div>
            <div class="form-group"><label for="id_category">Category:</label>
                {{ form.category }}</div>
            <div class="form-group"><label for="id_sub_category">Sub category:</label>
                {{ form.sub_category }}</div>
            <div class="form-group"><label>Tags:</label>
                {{ form.tags }}</div>


            <button type="submit">submit</button>
        </form>
    </div>
</section>

</body>
</html>